### ISSUE TITLE
Mob drops not prevented; massive dog spawns

### ISSUE THREAD

**Issue by SXRWahrheit** [garbagemule/MobArena#654] opened 2020-12-06 03:42 UTC
**Short description**

Mob drops aren't being prevented, allowing players to accumulate bones and spawn wolves/dogs.

**Reproduction steps**

1. Join an arena with /ma join
2. Kill skeletons, acquire bones
3. Wolf army

![2020-12-05_21 34 57](https://user-images.githubusercontent.com/774463/101270831-96110880-3742-11eb-97dc-f77327a5d0a8.png)

**Details**

* **MobArena version**: 0.105
* **Server version**: Paper 1.16.4 247

**Additional info**
The server is also running MythicMobs, which provides additional drops for vanilla mobs, but does so using the appropriate API procedures and should be properly cancelled if handled correctly by MobArena.

**Comment by garbagemule** [comment] 2020-12-06 09:54
I can't reproduce this in a clean Spigot 1.16.4 environment, nor in a clean paper-1.16.4-384 environment.

I bumped the skeleton probability of the first default wave to fight a bunch of those bastards off, but none of them dropped anything. I even tried with Looting III and Sharpness V to plow through more of them faster, but nothing dropped. It's most likely another plugin interfering, or a bug in Paper that has been fixed since 247.

I'm gonna close the issue because I don't think there is a bug in MobArena here. If you can reproduce on a clean setup with no other plugins, feel free to reopen! If you find out that it's a different plugin interfering, please report back which one it is, and maybe we can add a FAQ entry about it :)

**Closed by garbagemule** 2020-12-06 09:54 UTC
