### ISSUE TITLE
MyItems inventory deleted on arena end

### ISSUE THREAD

**Issue by LaBarata** [garbagemule/MobArena#640] opened 2020-08-30 14:58 UTC
# Bug report

**Short description**

When joining the arena with the MyItems class, the Player inventory is erased when the arena ends.

**Reproduction steps**

1. Join an arena with /ma join
2. Hit a sign to pick MyItems class
3. Lose or force end the arena

**Details**

* **MobArena version**: Latest dev build
* **Server version**: Paper Version git-paper-116 (Mc: 1.16.1) (implementing API version 1.16.1-R0.1-SNAPSHOT) 
* **Stacktrace** (if applicable): 

**Additional info**

**Comment by Chew** [comment] 2020-08-30 15:27
Please specify what version of Paper and the minecraft version associated.

**Comment by LaBarata** [comment] 2020-08-30 17:36
> Please specify what version of Paper and the minecraft version associated.

Done, sorry

**Comment by garbagemule** [comment] 2020-08-31 18:25
I can't reproduce this on Paper 174 with the MobArena build from the #test-builds channel on Discord. I tried being in creative mode and in survival mode with no other plugins than MobArena.

If we can't reproduce the issue on a clean setup with nothing but MobArena running, it is very likely a plugin conflict of sorts. It could be multi-inventory plugins messing around, or it could be a server bug.

**Comment by garbagemule** [comment] 2020-10-18 14:29
@LaBarata did you ever get around to figuring out what the culprit here was?

**Comment by garbagemule** [comment] 2021-03-03 09:06
Gonna close this because I still can't reproduce it. Feel free to reopen or hop on Discord for a troubleshooting session if the issue persists.

**Closed by garbagemule** 2021-03-03 09:06 UTC
Labels: area/restoration, blocked/feedback, type/bug
