### ISSUE TITLE
[BUG] No Title Display for Players using 1.16+

### ISSUE THREAD

**Issue by fireheart3911** [garbagemule/MobArena#728] opened 2022-03-29 15:25 UTC
# Bug report

**Short description**

No Titles are displayed for players using 1.16 or above (1.8 does work, cant confirm for 1.9 to 1.15).

**Reproduction steps**

1. Join an arena using 1.16 or above
2. Hit a sign to pick a class
3. Start the game
4. No titles are displayed

**Details**

* **MobArena version**: latest
* **Server version**: Paper (Release 408) // 1.17.1-R.01-SNAPSHOT
* **Stacktrace** (if applicable): -/.

**Additional info**

I found a temporary workaround: A repeating command block running `/title @a[distance=..599] title ""`

**Comment by garbagemule** [comment] 2022-03-29 16:50
Duplicate of #683.

**Closed by garbagemule** 2022-03-29 16:50 UTC
