### ISSUE TITLE
MobArena interferes with other plugins teleport event cancellation

### ISSUE THREAD

**Issue by minoneer** [garbagemule/MobArena#515] opened 2019-02-15 12:08 UTC
# Bug report

**Short description**
When any other plugin cancels the PlayerTeleportEvent, MobArena uncancels the event afterwards. Tested with end gateways - player was not in an arena (neither the location nor joined via command).

**Reproduction steps**
1. Load a plugin with a teleport listener that cancels player teleport. Then load mobarena. Teleport player - the event will not be cancelled.

**Details**

* **MobArena version**: 0.103.1
* **Server version**: git-Paper-522 (MC: 1.13.2)

**Additional info**
I believe it is caused by this line: https://github.com/garbagemule/MobArena/blob/master/src/main/java/com/garbagemule/MobArena/listeners/MAGlobalListener.java#L359

**Comment by garbagemule** [comment] 2019-02-15 16:03
Thanks for the bug report!

Just to make sure I understand... The issue here isn't that MobArena doesn't behave as it should *in the context of MobArena itself*, but rather than it *overreaches* and breaks some sort of functionality outside of its own context, right?

So, MobArena sometimes cancels PlayerTeleportEvents that it shouldn't? The provided link shows the exact line that cancels the event, but it isn't the root cause. Teleports are pretty complex to deal with, so MobArena basically asks every arena "is it okay if this player teleports?", and if *any* arena says "yes", it uncancels the event to make sure other plugins don't mess with MobArena trying to move players around (it needs to be able to move them to and from arenas).

To understand when an arena would answer "yes", we have to look into the arena-specific listener to see where it returns "ALLOW" rather than "REJECT" or "IDGAF". This happens in two places:

- [Before region checks](https://github.com/garbagemule/MobArena/blob/master/src/main/java/com/garbagemule/MobArena/ArenaListener.java#L1218), if the player is in a "moving state" (i.e. moving to or from the arena, or from the lobby to the arena floor), or if the player has the `mobarena.admin.teleport` permission (defaults to `true` for ops IIRC).
- [During region checks](https://github.com/garbagemule/MobArena/blob/master/src/main/java/com/garbagemule/MobArena/ArenaListener.java#L1218), if the player is actually part of the arena (on the arena floor or in the lobby) and moving from one part of the region to another.

From this analysis, I'd say that the underlying problem is with the `mobarena.admin.teleport` permission. Can you try to negate that permission to see if that fixes the problem?

**Comment by minoneer** [comment] 2019-02-15 21:25
Hey, thanks for the quick reply!

> Just to make sure I understand... The issue here isn't that MobArena doesn't behave as it should _in the context of MobArena itself_, but rather than it _overreaches_ and breaks some sort of functionality outside of its own context, right?

This is correct. When playing mobarena itself, everything behaves as expected. The problem occurs with teleports completely unrelated to any mobarena.

> So, MobArena sometimes cancels PlayerTeleportEvents that it shouldn't?

The oppisite is the case - MobArena _allows_ teleports that other plugins have cancelled - that is it sets cancelled to _false_ even though a different plugin previously set it to _true_.

> From this analysis, I'd say that the underlying problem is with the `mobarena.admin.teleport` permission. Can you try to negate that permission to see if that fixes the problem?

I can confirm that this is the case. In the original test I had the `*` permission (wildcard for all permissions) set for my account. Without that permission (which also implicitly unsets the `mobarena.admin.teleport` permission) the teleport remains cancelled, i.e. MobArena no longer interferes with the other plugin.

I can understand that sometimes forcing the event to be uncancelled for moving players to and from the arena is necessary to keep other plugins from interfering. But I don't see a reason to uncancel it based on a permission. Having a permission to _not cancel_ teleports for OPs inside an arena is great - but actively _uncancelling_ previously already cancelled events makes no sense IMO.

Thanks for looking into it!

**Comment by garbagemule** [comment] 2019-02-16 01:56
Ah, I typed the opposite of what I was thinking in that first line. But it looks like I understood the problem.

I think the issue can be solved by moving the permission check down into the region checks, such that MobArena only rejects the teleport in the places that it currently rejects them in if the player doesn't have the permission, and otherwise responds with an IDGAF.

You seem to be code savvy - would you like to take a stab at solving the issue in a pull request? :)

**Comment by garbagemule** [comment] 2019-02-16 12:21
Actually, I think just moving the permission check out into the MAGlobalListener before the arena loop would solve the issue as well. It's essentially a short-circuit permission that should tell MobArena to leave the event alone and let whatever happens happen. If the player can't teleport despite having this permission, it's a different plugin interfering and thus not MobArena's problem to deal with. Is that a sound conclusion?

I jumped right at an implementation. It's completely untested, but I've got a build ready for you to test if you want to hop on Discord and grab it :)

**Comment by minoneer** [comment] 2019-02-16 14:44
> Ah, I typed the opposite of what I was thinking in that first line. But it looks like I understood the problem.

Yeah, that's what I thought. Just wanted to make it clear to avoid confusion.

> You seem to be code savvy - would you like to take a stab at solving the issue in a pull request? :)

I could have - but apparently you already got it covered ^^

> Actually, I think just moving the permission check out into the MAGlobalListener before the arena loop would solve the issue as well. It's essentially a short-circuit permission that should tell MobArena to leave the event alone and let whatever happens happen. If the player can't teleport despite having this permission, it's a different plugin interfering and thus not MobArena's problem to deal with. Is that a sound conclusion?

Yes, I think that's a valid approach. Players with the MA override permission should usually also have other teleport override permissions so there should be no interference with MA teleports.

Another valid approach I see would be to check the permission right before cancelling a teleport. That way it still retains the current behaviour of enforcing teleports within the arena for all players (even those with the override permission) but stops MA from cancelling any other teleports within the arena for those with the override permission. Both approaches would be fine for me.

I tested the build from discord - it no longer interferes with the other plugin. Thanks a lot for the quick fix!

**Comment by garbagemule** [comment] 2019-02-16 15:09
Hmm, your suggestion is definitely a more "exact" solution to the problem. By removing the permission check from the arena listener code, the problem is fixed. But to preserve the permission semantics, the check has to happen somewhere else, and maybe it makes more sense for the check to just result in MobArena not canceling in situations where it normally would. Sounds more intuitive than a flat out "ignore" I guess.

**Comment by minoneer** [comment] 2019-02-16 15:21
I don't see the changes you made anywhere, but this change should do it:

```diff
// Only cancel if at least one arena has rejected the teleport.
- if (!allow) {
+ if (!allow && !player.hasPermission("mobarena.admin.teleport")) {
    event.setCancelled(true);
}
```
https://github.com/garbagemule/MobArena/blob/fc8debca296fc770aa16d7f76cf4489ac4ddab50/src/main/java/com/garbagemule/MobArena/listeners/MAGlobalListener.java#L369

And removing the previous override check of course.

**Closed** 2019-02-16 16:36 UTC
Labels: bug, needs feedback
