### ISSUE TITLE
Set time interval before next wave

### ISSUE THREAD

**Issue by Oruss7** [garbagemule/MobArena#481] opened 2018-07-23 11:21 UTC
# Feature request

**Short description**
Please set time interval before next wave. 
I have `clear-wave-before-next: true` but when last mob is killed, next wave spawn immediatly and creeper for example blow up players... A interval time before last mob killed and next wave spawn will be appreciated.

**Implementation details**
Maybe add a new config (in second):
`clear-wave-time-before-next: 20`

**Additional info**
conf: https://pastebin.com/c5qzpjPq

Thanks you !

**Comment by garbagemule** [comment] 2018-07-29 13:39
Duplicate of #449

**Closed by garbagemule** 2018-07-29 13:39 UTC

**Comment by garbagemule** [comment] 2018-07-29 15:20
@Oruss7 as mentioned on #449 I can give you a build with an implementation of this feature on Discord if you want :)

**Comment by Oruss7** [comment] 2018-07-30 17:49
yes i want ! thanks @garbagemule and all team MobArena !
