### ISSUE TITLE
[suggestion] aggro range

### ISSUE THREAD

**Issue by Longhair1996** [garbagemule/MobArena#264] opened 2015-03-10 20:14 UTC
would it be possible to have the aggro range set so that a mob can detect a player from anywhere within the arena, including the ability to detect through walls?

**Comment by garbagemule** [comment] 2015-03-10 22:56
Unless things have changed since last time I checked (admittedly it's been at least half a year), it's not possible, no. The problem is that the Minecraft internals/Bukkit API don't allow it, and setting the target of a mob further than 16 blocks freezes the mob in place until the player comes close. You can see this effect in very early MobArena gameplay videos where the mobs are just frozen until someone hits them or their specific target gets within range.

**Comment by Buckmanfu** [comment] 2017-06-05 18:06
The issue is due to Spigot/Bukkit.  There is a item in the spigot.yml for entity activation range.  Basically to reduce load on the server range where the mob AI is turned off is reduced.  

I don't know if this could be configured per world and have the arena running in a Multi-Verse set up and have a different server configuration.  Having the config per world might have to go to MV or Spigot dev team.

**Comment by ct-martin** [comment] 2017-12-26 21:07
Closing in favor of #412 which has a more complete discussion of the issue.

**Closed by ct-martin** 2017-12-26 21:07 UTC
Labels: enhancement
