### ISSUE TITLE
MythicMobs Extension

### ISSUE THREAD

**Issue by xPaZzyy** [garbagemule/MobArena#631] opened 2020-07-16 17:25 UTC
**Short description**

We should have a MobArena Extension plugin, made and maintained by GarbageMule.

**Implementation details**

It would allow for MythicMobs to spawn in the MobArena.

**Additional info**
Should load the Extension AFTER mobarena loads, unlike Sait's extension that loads before mobarena.

**Comment by garbagemule** [comment] 2020-07-16 17:46
Arguably a duplicate of #362. The _how_ and the _who_ aren't so important.

**Closed by garbagemule** 2020-07-16 17:46 UTC
