### ISSUE TITLE
Need Help with Lingering Potions and Enchantments ID ( sweeping edge)

### ISSUE THREAD

**Issue by Jarpox** [garbagemule/MobArena#424] opened 2018-01-09 21:51 UTC
# Summary

* This issue is a…
    * [ ] Bug report
    * [ ] Feature request
    * [ ] Documentation request
    * [X ] Other issue
    * [x ] Question
* **Describe the issue / feature in 1-2 sentences**: Please I need a list for enchantments (sweeping edge to be specific) and id for spectral arrows and lingering potions for my classes in the config. Thank you for the support, after days of searching for options this is my only hope.

# Background

### Bug report

* **MobArena version**: 
* **Server version**: 
* **Plugins**: 

### Feature request 

* **Feature type**:
    * [ ] Arena configuration
    * [ ] Classes
    * [ ] Documentation
    * [ ] Economy integration
    * [ ] Leaderboards
    * [ ] New config settings
    * [ ] Other (please explain)
    * [ ] Rewards
    * [ ] Third-party plugin support

**What does it do?**: 

**Does it need new or changed commands? What are they?**: 

**Does this feature affect other parts of MobArena?**: 

# Details

* **Stacktrace** (if applicable):

**Comment by jflory7** [comment] 2018-01-15 01:40
@Jarpox A list of all enchantments is [here](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/enchantments/Enchantment.html) in the Spigot documentation.

We will have a page with new info with our documentation too (will be [here](https://mobarena.readthedocs.io/en/latest/user/item-reward-syntax.html)). A "preview" of it, with the correct info, is [here](https://github.com/CrystalCraftMC/MobArena/blob/624087b01330c8d6c3cd2efee2aa0153cf6438c9/docs/user/item-reward-syntax.rst).

Closing this issue since it is a question and not a bug.

**Closed by jflory7** 2018-01-15 01:40 UTC
Labels: question
