### ISSUE TITLE
Players are able to join the arena again before it kicks them out on end.

### ISSUE THREAD

**Issue by mibby** [garbagemule/MobArena#528] opened 2019-04-23 10:04 UTC
Paper dev 624 (Spigot 1.13.2)
MobArena v0.103.2-SNAPSHOT (discord test build 02/16/19)

Players seem to be able to join the MobArena again while in a spectate state before the arena ends and kicks everyone out to their old location when joining from death spectate state.

i.e. - Player joins MA, loses, gets kicked to spectate death location, then joins MA again from within spectate before it kicks them out. MobArena freaks out and teleports them across worlds multiple times.

> World > Void > (/ma j before kicked out) > world > void > world > void

Whereas if they don't join from within the death spectate location, it should behave normally;
> World > Void > World
> (Join > Play > End)

I assume this is also a symptom of some users complaining about inventory loss when playing MobArena since they are joining before MA tries to restore their contents -- saving a new snapshot of their empty spectate inventory.

Would it be possible to add an option to disable joining the MobArena while you are spectating when a game ends? So players can only safely join the MobArena when it is not active and they are outside the arena location.

**Comment by garbagemule** [comment] 2019-04-23 11:13
Okay, I'm gonna need some clarification, because I don't understand what the problem is and what is happening.

- What do you mean by "join the MobArena"? How many arenas are involved? Is it just one? Is it the same one?
- What is that "kicks everyone out"? When does this happen and how? There are two reasons MobArena will "kick" someone out; one is force ending the arena, the other is if the arena has a final wave. What's going on?
- If you're spectating an arena, MobArena will first force a leave before it tries to do anything else. If the arena you're trying to join is running, you won't join and nothing will happen. It'll just tell you that the arena is running and not attempt any teleporting.
- What is "World" and "Void"?

The reason the template asks for reproduction steps is because without them, I'm left throwing guesses at an empty wall. I'm not gonna do that. Describe a setup I can actually replicate and reproduce the issue with, and make it minimal (Spigot [not Paper], MobArena, nothing else if at all possible). Otherwise the issue is just gonna drown.

If there is an issue that needs to be fixed, I want to fix it. I don't want to add config-file settings as workarounds.

**Comment by mibby** [comment] 2019-04-23 11:43
* Just a singular arena exists. Players join via the command ``/ma j``.
* MobArena should "kick everyone out" back to their old location when the arena ends without any remaining players alive.
* I do not believe anyone is intentionally joining the spectate state. The issue occurrence is when players are brought to spectate on death, then are able to re-join the arena when the arena is in the process of kicking everyone out due to game end / no alive players. Somehow players are able to re-join from the spectate location during the period of MA attempting to end / kick them out to their joining location. By doing so, they get stuck in a teleport loop and have on rare occurrence had their inventory lost (overwritten empty with spectate inventory).
* For simplicity sake, ``world`` is the separate world location players are joining from, ``void`` is the world where the arena is located.

**Comment by garbagemule** [comment] 2019-04-23 15:23
> * MobArena should "kick everyone out" back to their old location when the arena ends without any remaining players alive.

It doesn't. When a player dies, they either auto-leave or auto-spectate, and that depends on the `spectate-on-death` setting. When an arena ends, it just wipes its own state - it doesn't "do anything" to players. When an arena reaches its final wave, if set, it forces a player leave (same as players typing /ma leave) on everyone still in the arena. It doesn't touch the spectators.

> * ... The issue occurrence is when players are brought to spectate on death, then are able to re-join the arena when the arena is in the process of kicking everyone out due to game end / no alive players. Somehow players are able to re-join from the spectate location during the period of MA attempting to end / kick them out to their joining location.

This doesn't make any sense. MobArena's end process is completely synchronous. It isn't possible to join while the arena is ending, because "ending" is - in terms of the event queue/command processing - an atomic operation. You either join before or after ending, not "while" ending.

As for joining from the spectator area - that's perfectly valid. MobArena will force a leave when you type /ma join, and then do a normal join. So what happens in that case is that you get thrown out to your join location due to the leave, and then back into the lobby due to the join. If the join location is in a different world, this incurs two world changes. This is intentional, because assuming all other plugins are doing their job properly with respect to the event queue, a leave + join will correctly restore the player's state on leave and store it on join. Partial restore/store is what caused all the old inventory-related issues.

The title of this issue makes it sound like MobArena isn't locking down its sessions after they've started, allowing players to join after dying. It sounds like the underlying issue is an inventory plugin handling world changes asynchronously.

**Comment by garbagemule** [comment] 2019-12-31 19:58
Gonna close this issue as I can't see any way forward without more feedback. Feel free to reopen if it's still relevant.

**Closed by garbagemule** 2019-12-31 19:58 UTC
Labels: needs feedback
