### ISSUE TITLE
MA crash when item sets health below 20

### ISSUE THREAD

**Issue by ElderMiner** [garbagemule/MobArena#545] opened 2019-07-12 15:38 UTC
# Bug report

**Short description**

MA crashes if joining while having an item that lowers health below 20

**Reproduction steps**

1. have item that modifies health below 20:
`/minecraft:give ElderMiner minecraft:golden_sword{display:{Name:"{\"text\":\"Black Bones' Sword\",\"color\":\"dark_red\",\"italic\":false}",Lore:["An ancient and evil sword","it's power flows through you but it ","knows you are not its true master"]},AttributeModifiers:[{AttributeName:"generic.maxHealth",Name:"generic.maxHealth",Slot:"mainhand",Amount:-10,Operation:0,UUIDMost:78996,UUIDLeast:173386},{AttributeName:"generic.movementSpeed",Name:"generic.movementSpeed",Slot:"mainhand",Amount:1.5,Operation:1,UUIDMost:19996,UUIDLeast:170096},{AttributeName:"generic.knockbackResistance",Name:"generic.knockbackResistance",Slot:"mainhand",Amount:100,Operation:0,UUIDMost:69286,UUIDLeast:127509}],RepairCost:-2147483648,Enchantments:[{id:"minecraft:unbreaking",lvl:2},{id:"minecraft:sharpness",lvl:10}]} 1`
2. join MA
3. Error appears in console:

https://pastebin.com/QPiLKYy7

* **MobArena version**: 0.103.2
* **Server version**: paper Update 637

**Comment by garbagemule** [comment] 2019-07-12 16:14
Please fix the formatting issues (use pastebin as per the template guide) and fill out the missing bits and pieces. Thanks!

**Comment by ElderMiner** [comment] 2019-07-13 00:08
I think its updated to how you wanted it,

**Comment by ElderMiner** [comment] 2019-07-13 01:53
> Please fix the formatting issues (use pastebin as per the template guide) and fill out the missing bits and pieces. Thanks!

I think its updated to how you wanted it,

**Comment by garbagemule** [comment] 2019-07-14 19:49
Thanks!

The last time this was reported, it was fixed and confirmed fixed by someone from the community. It's weird that it crops up again. It's not unlikely that the API or the inner workings of Minecraft have changed, and it's not unlikely that it's a bug in Paper either. I think we need to dig a bit deeper.

First I need to know how to get an item that modifies health below 20. Preferably a full vanilla command I can just plop into my game to see the error reproduced. Feel free to update the reproduction steps with this command/step :)

**Comment by ElderMiner** [comment] 2019-07-14 19:56
> Thanks!
> 
> The last time this was reported, it was fixed and confirmed fixed by someone from the community. It's weird that it crops up again. It's not unlikely that the API or the inner workings of Minecraft have changed, and it's not unlikely that it's a bug in Paper either. I think we need to dig a bit deeper.
> 
> First I need to know how to get an item that modifies health below 20. Preferably a full vanilla command I can just plop into my game to see the error reproduced. Feel free to update the reproduction steps with this command/step :)

this is the exact item i am using:

/minecraft:give @p minecraft:golden_sword{display:{Name:"{\"text\":\"Black Bones' Sword\",\"color\":\"dark_red\",\"italic\":false}",Lore:["An ancient and evil sword","it's power flows through you but it ","knows you are not its true master"]},AttributeModifiers:[{AttributeName:"generic.maxHealth",Name:"generic.maxHealth",Slot:"mainhand",Amount:-10,Operation:0,UUIDMost:78996,UUIDLeast:173386},{AttributeName:"generic.movementSpeed",Name:"generic.movementSpeed",Slot:"mainhand",Amount:1.5,Operation:1,UUIDMost:19996,UUIDLeast:170096},{AttributeName:"generic.knockbackResistance",Name:"generic.knockbackResistance",Slot:"mainhand",Amount:100,Operation:0,UUIDMost:69286,UUIDLeast:127509}],RepairCost:-2147483648,Enchantments:[{id:"minecraft:unbreaking",lvl:2},{id:"minecraft:sharpness",lvl:10}]} 1

**Comment by garbagemule** [comment] 2019-07-14 19:58
Awesome, thanks. I'll take a look at this when I find some time (vacation coming up) :)

**Comment by SaitDev** [comment] 2019-07-15 01:59
since it -10 to the base atribute value I think we can use `getAttribute(Attribute.GENERIC_MAX_HEALTH).getValue()` instead 
https://github.com/garbagemule/MobArena/blob/93af93d5a0d8bc6672435b4cb3932db08ae162f2/src/main/java/com/garbagemule/MobArena/steps/SetHealth.java#L27

**Comment by garbagemule** [comment] 2019-07-15 14:57
@SaitDev I thought that might be the case, but I wasn't sure if there was a specific reason for picking getBaseValue instead of getValue. If you have a few examples of how the different values work, I'd love to hear them. I don't think the API is very clear on what the methods actually return. 

Elder is on the Discord as well, so if you have a test build I think you can just throw it at him :)

**Closed** 2019-07-21 21:12 UTC
Labels: bug, needs feedback, needs investigation
