### ISSUE TITLE
Player scoreboard groups do not restore when leaving the MobArena while in battle.

### ISSUE THREAD

**Issue by mibby** [garbagemule/MobArena#387] opened 2017-07-05 22:47 UTC
MobArena v0.98.2

```
      use-scoreboards: true
```

I colorize player nametags with another plugin so their nametag above their head is colored based on their group prefix. This is done by setting players to specific scoreboard groups.

When a player joins the MobArena and leaves via ```/ma leave``` while in battle, their scoreboard does not restore to their old groups.

**Comment by ct-martin** [comment] 2017-12-26 20:40
Duplicate of #366

**Closed by ct-martin** 2017-12-26 20:40 UTC
