### ISSUE TITLE
Incompatible with Spigot 1.13.

### ISSUE THREAD

**Issue by mibby** [garbagemule/MobArena#487] opened 2018-08-18 20:35 UTC
I've been testing out a bunch of plugins in a new 1.13 environment to see what breaks. Just thought I'd let you know about this error for when you update to 1.13. :)

MobArena compiled as of commit https://github.com/garbagemule/MobArena/commit/548d8c7e4fe670e857f27c9b484f897e6f38df77
Paper-1.13 dev 152 (Spigot 1.13)

```
[13:07:59] [Server thread/INFO]: [MobArena] Enabling MobArena v0.102.1-SNAPSHOT*
[13:07:59] [Server thread/ERROR]: Error occurred while enabling MobArena v0.102.1-SNAPSHOT (Is it up to date?)
java.lang.IllegalStateException: Incompatible server version! This build only works on [1.11, 1.12], but this server is running 1.13. Perhaps you downloaded the wrong build?
	at com.garbagemule.MobArena.ServerVersionCheck.check(ServerVersionCheck.java:32) ~[?:?]
	at com.garbagemule.MobArena.MobArena.onEnable(MobArena.java:72) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.13.jar:git-Paper-152]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325) ~[patched_1.13.jar:git-Paper-152]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.13.jar:git-Paper-152]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:433) ~[patched_1.13.jar:git-Paper-152]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:347) ~[patched_1.13.jar:git-Paper-152]
	at net.minecraft.server.v1_13_R1.MinecraftServer.m(MinecraftServer.java:589) ~[patched_1.13.jar:git-Paper-152]
	at net.minecraft.server.v1_13_R1.MinecraftServer.g_(MinecraftServer.java:551) ~[patched_1.13.jar:git-Paper-152]
	at net.minecraft.server.v1_13_R1.MinecraftServer.a(MinecraftServer.java:428) ~[patched_1.13.jar:git-Paper-152]
	at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:305) ~[patched_1.13.jar:git-Paper-152]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:764) ~[patched_1.13.jar:git-Paper-152]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[13:07:59] [Server thread/INFO]: [MobArena] Disabling MobArena v0.102.1-SNAPSHOT

```

**Comment by garbagemule** [comment] 2018-08-18 20:37
Duplicate of #479 

Dev builds on Discord. Come test :)

**Closed by garbagemule** 2018-08-18 20:37 UTC
