### ISSUE TITLE
MobArena Death Glitch

### ISSUE THREAD

**Issue by MMooseyyy** [garbagemule/MobArena#476] opened 2018-07-11 21:14 UTC
# Bug report

**Short description**
 After you die in any of the mob arenas, the death animation does not go away. Only you can see it however. When you go in third person you can see it, and when you go into your inventory you can see it. This has been an issue for some time, and we have not been able to find a fix.

When I join the arena, X doesn't work.

**Reproduction steps**

1. Join an arena with /ma join
2. Hit a sign to pick a class
3. Error appears in console

**Details**

* **MobArena version**: 0.1.2
* **Server version**: Spigot 3.4.5
* **Stacktrace** (if applicable): https://pastebin.com/gB5qbcnr

**Additional info**

**Comment by garbagemule** [comment] 2018-07-11 21:28
Duplicate of #437

**Closed by garbagemule** 2018-07-11 21:28 UTC
