### ISSUE TITLE
Pigzombies aggro the player, but doesn't run until hit.

### ISSUE THREAD

**Issue by Nesseley** [garbagemule/MobArena#561] opened 2019-07-31 16:17 UTC
# Bug report

**Short description**
When a pig zombie spawn it aggro the player, but it walks in non-aggro speed until hit by a player. Only then will it start to run.
Pigzombies should always run when aggro.

**Reproduction steps**
1. Have a wave that includes pig zombies.
2. See that they walk towards you.
3. Hit one, it should now run after you instead of walking.

**Details**
* **MobArena version**: 0.103.3-SNAPSHOT (Test-build from Discord, posted Sunday 28th july.)
* **Server version**: CraftBukkit version git-Spigot-1981d55-da62a66 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
* **Stacktrace**: none

**Comment by garbagemule** [comment] 2019-08-02 12:31
Looks like there has been "anger" on pig zombies since 2011 according to the Spigot commit history. Is this also an issue on 1.13?

**Comment by lukacat10** [comment] 2019-08-03 15:37
I can confirm this occurs on 1.13
It is a pretty minor speed change though

**Comment by garbagemule** [comment] 2019-08-03 15:43
@lukacat10 would you be interested in helping test out a fix for this? If so, please hop on Discord and ping me :)

**Closed** 2019-08-03 18:33 UTC
Labels: bug
