### ISSUE TITLE
Killer Bunnies temporarily froze server

### ISSUE THREAD

**Issue by Pugabyte** [garbagemule/MobArena#432] opened 2018-03-04 16:37 UTC
# Summary

* This issue is a…
    * [x] Bug report
    * [ ] Feature request
    * [ ] Documentation request
    * [ ] Other issue
    * [ ] Question
* **Describe the issue / feature in 1-2 sentences**: 
    Killer Bunnies in MA appear to have frozen the server.

    `_leroy > idk what happened but i ended up getting the actual death screen and then everything died` 

    This only happened once, about a month ago, the MA has been in use since then multiple times and it has not happened again to my knowledge.

# Background

### Bug report

* **MobArena version**: 0.99.1-SNAPSHOT
* **Server version**: 1.12.2
* **Plugins**: `PlugMan, AutomaticInventory, Murder, SimpleAPI, SidewaysLogFix, wget, AutoMessage, MinigameHandler, Chairs, ProtocolLib, CustomParticleEffects, bnCore, MVdWPlaceholderAPI, FastAsyncWorldEdit, PermissionsEx, FeatherBoard, WhatIs, Tab, ServerListPlus, PlaceholderAPI, OneWayBlocks, InventoryChess, ActionBar, VoxelSniper, EditableSign, Alerts, TimeLock, StopPushing, dynmap, WorldEdit, OpenInv, WorldBorder, BuycraftX, Votifier, LibsDisguises, eZProtector, Super_Elytra, SQLibrary, DotCommand, Vault, TitleAdvanced, LWC, Quake, PlayerPoints, ChestCommands, PlayerVaults, MyCommand, GAListener, Herochat, Trading, PlotSquared, WorldGuard, ASkyBlock, Prism, Essentials, HeadDatabase, LiteBans, Dynmap-ASkyBlock, VanishNoPacket, Plot2Dynmap, CustomEnchantments, ConditionalPerms, SimplePets, Multiverse-Core, Citizens, mcMMO, MiniaturePets, MobArena, EssentialsProtect, Multiverse-Inventories, EssentialsAntiBuild, ParticleHats, EssentialsSpawn, WorldGuardExtraFlags, Denizen, PurpleIRC, PreciousStones, HeavySpleef, EnjinMinecraftPlugin, PermHelper, KillerMoney, HolographicDisplays, Depenizen, VoxelSniperRegions, Multiverse-NetherPortals, MultiWorldMoney, Minigames, Minigames-Regions`

# Details

* **Stacktrace** (if applicable): http://paste.bear-nation.net/fagoj.md

* **Config**: https://github.com/Pugabyte/ServerFiles/blob/master/MobArena/config.yml#L1933-L2082

**Comment by garbagemule** [comment] 2018-04-07 13:44
Hey Pugs. Has this happened again in the past month?

There's a long-standing issue with deaths/disconnects and the scoreboard manager, and it looks like that's the last place MobArena was doing anything before the crash. It's unlikely that MobArena would crash the server, because plugins are pretty well sandboxed. I think it's more likely that this is a host issue like memory or network.

**Comment by Pugabyte** [comment] 2018-04-24 17:11
I feel it is unlikely that it was a memory issue. I stay pretty ontop of the system to make sure there's always memory and CPU free. 
![image](https://user-images.githubusercontent.com/12417961/39202670-97bf91b6-47c0-11e8-8096-90aeb86f50d4.png)

It could have been a network issue, I cannot say for certain it wasn't, but my host has been extremely reliable through the 3 years I've used it (OVH division SoYouStart)

**Comment by garbagemule** [comment] 2018-04-24 19:47
So the only thing I can think of that would make stuff freeze is the cleanup code due to the entity/region scans. Maybe it would be worth looking into logging some timings of some of these things?

It could also be that a GC cycle kicked in - 3 gigs is a lot of heap space to clean up if the usage isn't normally up there and all of a sudden there's a ton of objects to nuke.

**Comment by garbagemule** [comment] 2018-05-06 17:49
I'm gonna close this as it isn't really possible to get any further. We can't reproduce it, and it doesn't look like it's happened ever since.

**Closed by garbagemule** 2018-05-06 17:49 UTC
