### ISSUE TITLE
Can't use wither skeletons in 1.8

### ISSUE THREAD

**Issue by iceypotato** [garbagemule/MobArena#474] opened 2018-07-05 20:03 UTC
# Bug report

**Short description**
For the boss wave, I put monster: wither_skeleton as the mob, but in the console, it says it cannot parse the monster for boss#.

**Reproduction steps**
put this in the config file right under the waves: single: section of the arena.

        boss5:
          type: boss
          wave: 30
          monster: wither-skeleton
          health: 1250
          abilities: shuffle-positions, throw-nearby, obsidian-bomb

**Details**

* **MobArena version**: 0.101
* **Server version**: Spigot for MC 1.8.8
* **Stacktrace** (if applicable): none

**Additional info**
I think it worked in older versions of mobarena.

**Comment by Nesseley** [comment] 2018-07-05 20:06
Hey!
Not sure if you noticed but you typed wither-skeleton, not wither_skeleton in the Reproduction steps. Use a underscore not a hyphen for it to work. ^^
Could this be your mistake?

**Comment by garbagemule** [comment] 2018-07-05 20:07
There is no Spigot 3.4.5 - please update the issue with the server version you're running.

**Comment by iceypotato** [comment] 2018-07-05 23:42
Sorry, I am using spigot 1.8.8

**Comment by garbagemule** [comment] 2018-07-06 11:01
Right, wither skeletons work perfectly fine in 1.11-1.12, because they have their own EntityType. As per the update to 1.11 about one and a half years ago, the wither skeleton-specific logic was removed (3b88b889d6c94356992f88221be719ec1a469e98). In the backport to 1.8.7 (94feabb9e3acddb121c3bef9f5ee7752d0d7c27f) when 1.8 support was being requested a lot, the wither skeleton logic was not carried over.

This isn't a bug but a missing feature, so I'm marking it as an enhancement. I do believe I have a fix, though, so if you (@iceypotato) can come on the MobArena Discord, I can send you a build that you can test out.

**Comment by garbagemule** [comment] 2018-07-19 00:33
Fixed in next release.

**Closed by garbagemule** 2018-07-19 00:33 UTC
Labels: enhancement
