### ISSUE TITLE
Disappearing wood and useless phantoms

### ISSUE THREAD

**Issue by Sandukhan** [garbagemule/MobArena#512] opened 2019-01-29 19:13 UTC
# Bug report

**Short description**

**_wooden blocks_**
There seems to be a problem with mobarena and wooden blocks, because they keep disappearing after a arena has been used. Not all at once but a random 1-3 after every run. They even keep disappearing after editing a arena, putting them back in place and for the most time its these same blocks again.
However thats only seems to be a issue with log and wood (oak_wood, spruce_wood... and oak_log, spruce_log....) of any kind, other blocks like wooden planks or stone are doing fine. 

**_phantoms and drowned_**
Also phantoms and drowned cant realy be used in mobarena. Phantoms burn during the day and die and drowned dont attack players during the day. 

**Details**

* **MobArena version**: v0.103.1
* **Server version**: Spigot 1.13.2

**Comment by Nesseley** [comment] 2019-01-29 19:15
I had this problem when using TOWNY's regen feature.

**Comment by Sandukhan** [comment] 2019-01-29 19:16
We dont use Towny on my server.

**Comment by garbagemule** [comment] 2019-01-29 19:17
Can you reproduce it on a clean setup with just MobArena and no other plugins?

**Comment by Sandukhan** [comment] 2019-01-29 21:02
I did some quick tests now and with mobarena as only plugin on the server i didnt run in the same issues with wooden blocks yet. I startet to add more plugins, that could meddle with ma like worldedit and worldguard, but nothing so far.
Im still a bit suspicious of logblock, since i hadnt the proper database setup for that on my test server, but thats just a guess. 

I coundnt see any connection, the blocks seems to disappearing inside a battlefield of arena, any area around that like the lobby, never had that problem. Its just wierd thats only a issue with log and wood inside a mobarena.

Phantoms and drowned however still behave like vanilla mobs, even with mobarena as single plugin on the server and default settings.

**Comment by garbagemule** [comment] 2019-01-30 00:16
It's really confusing to have two different and unrelated issues in the same issue.

The wooden block issue doesn't seem to be caused by MobArena. It could be that block breaks or explosions are cancelled, but whatever other plugin is interfering is trying to do its own restoration or something.

As for monster behavior, MobArena doesn't tinker with it in any way except by setting targets and by cancelling combustion that doesn't happen due to blocks or entities (so players and fire blocks can set fire to mobs, but the sun can't). Any behavior that doesn't "fit" in this very limited scope is unlikely to fit at all. We can't control monster AI in the Bukkit API (with NMS it is possible, but we can't go there), and the same goes for most of the properties of mobs. For instance, we can't make skeletons walk differently or make zombies fly. As such, phantoms and drowned probably just behave like they're supposed to. MobArena is already doing its part to cancel combustion and force attacks. I'm afraid that this might be Spigot bugs and/or behavior that can't be remedied without brittle hacks.

**Comment by garbagemule** [comment] 2019-02-09 21:00
Closing this because there isn't much we can do about either issue.

The monster behavior issue would probably be a good topic of discussion for the mobs rework once the sessions rework is done. But it's a much bigger topic than just phantoms and drowned, so it'll need a more thorough look.

**Closed by garbagemule** 2019-02-09 21:00 UTC
