### ISSUE TITLE
Per World Inventory is incompatible now

### ISSUE THREAD

**Issue by ScuroK** [garbagemule/MobArena#423] opened 2018-01-05 01:03 UTC
Hey there.

The latest version of PerWorldInventory is incompatible with many minigame plugins like mobarena and creates bugs like loosing inventories. Unfortunately the developer of PWI is very slow responding and there is no working alternative like PWI.

The developer of paintball said he had to add PWI as soft-dependency to fix this.

Please see all the details here:
https://github.com/Gnat008/PerWorldInventory/issues/292

**Comment by RainOfPain125** [comment] 2018-01-18 20:13
To shine some light on this real quick

Me and my OP buddy lost our survival inventories. Here's the step by step way we did it

1 - Have stuff in your survival inventory
2 - Have stuff in your creative inventory
3 - Do /ma join while in creative
4 - Picked a kit
5 - Did /ma leave
6 - Creative inventory was wiped
7 - Survival inventory became the new creative inventory - wiping everything in the survival inventory

**Comment by Nesseley** [comment] 2018-01-20 14:00
This has been around for years! Atleast since i found the creativeswitch bug in 2013.
The creative-inv switched is fixed by not letting people join mobarena from creative, or other worlds then the arena is in it self. This can easly be dine by setting the "max-join-distance:" in config.yml

**Comment by ct-martin** [comment] 2018-01-21 20:08
@ScuroK @RainOfPain125 as @Nesseley and @Gnat008 indicated, the best way to deal with this is to have the arena in its own world and prevent the player from jumping worlds directly. I also recommend having your server put the player in the world they were previously in when they rejoin.

**Comment by garbagemule** [comment] 2018-04-07 13:53
Hey guys, thanks for the bug report and sorry for the crazy delay.

I think it is worth revisiting inventories in the April sweep. I'll see how far I can get on a possible workaround/fix for this. I'd like a full rewrite of the join/leave logic, but it might not be feasible this time around.

@RainOfPain125 Is this a purely one-world setup, or is creative and survival in different worlds? If so, which world is MobArena in?

**Comment by RainOfPain125** [comment] 2018-04-08 01:34
@garbagemule This was in the Nether. I have mutiverse and are using multiple worlds, but everything to do with mob arena was kept in the Nether. The world is by default survival.

**Comment by garbagemule** [comment] 2018-04-23 09:35
Maybe we can establish the order in which MobArena does its stuff, just so I don't have to guess too much. It seems like changing gamemodes and worlds cause inventories to change. And it also seems like changing worlds may cause a change in gamemode as well, but not the other way around. So with that, does this order make sense for when a player joins?

- Record current location, then teleport to the lobby
- Record current gamemode, then switch to survival mode
- Record current health, hunger, level, experience, potion effects, then reset all of it
- Record current inventory, then clear it

Then when a player leaves, we restore in the exact reverse order:

- Restore inventory
- Restore health, hunger, level, experience, and potion effects
- Restore gamemode
- Teleport to where we joined from (or the exit warp)

The only thing I then don't know how to fit in is rewards. When and where do we grant rewards? Is it after restoring the inventory? In that case, rewards are limited to the same inventory as players have in the arena world in survival mode. So to use the rewards in a different survival world, the two inventories of the two worlds and gamemodes need to be the same. Is this something that's doable? Is that normal behavior?

I think I need a bit of help in understanding the typical use cases and limitations of the per-world and -gamemode plugins to come up with a rock solid order of operations.

**Comment by Nesseley** [comment] 2018-04-23 14:55
The thing they do is:
Be in the creative-world
use /ma join
Use /ma leave
They:
a) havent set the exit place
b) have set the exit in survival/other world than they can join from

Because of this the inventories will switch, as MobArena saves the inventory they JOINED with, and gives this (JOINED) inventory back when leaving (and when they leave they are placed in survival as the player/admin on server has set it ut that way) 

We already have multiple ways to prevent this issue. 
a) only let users join from x blocks away from the arena. This blocks joining from Creative.world.
b) only let users join when they are in the same world as the mobarena
c) dont set the exit in survival, or whatever. but use the option to place them where they joined form. Creative - mobarena - creative.
survival - mobarena - survival

**Comment by garbagemule** [comment] 2018-04-27 18:08
Just to sort of delegate the workload, is there any chance one of you guys could set up a super basic server environment with just the plugins and configuration of MobArena necessary to reproduce this, and then zip it and upload it somewhere? That way I don't have to spend a lot of time learning how to set up the plugins, and I can focus on fixing the issue.

I have a basic rework of the join/leave cycle in the works, close to being ready for testing. I'd like some help with testing, so if any of you are on Discord and want to help out, hop on over to the MobArena server and I'll send you a jar-file :)

**Comment by Nesseley** [comment] 2018-04-27 18:51
I guess I can set that up, whats the discord? :)

**Comment by garbagemule** [comment] 2018-04-29 03:40
@ScuroK @RainOfPain125 @Sikatsu 
I've just wrapped up an almost complete rewrite of the join/leave logic, and I've tested it on my local single-world setup, where it seems to work as expected. @Nesseley helped me test out an earlier build with some of the same ideas as this new build, but I gotta admit I have basically zero knowledge of how many ways a multi-world and multi-inventory setup could viably work, so I think it's absolutely essential that we get as many people on this as possible.

I want to include these changes in the April release if possible, so if any or all of you have time this weekend, it would be so helpful if you could test out the build with your own setups, perhaps try some deliberate "sabotage" of the plugin to try and break it, and report back here with your findings.

I'm especially interested how it behaves with `spectate-on-death` on/off, with `auto-respawn` on/off, and with/without exit warps in the arena (just remove the config-file entry to remove an exit warp).

The build is available on [Dropbox](https://www.dropbox.com/s/zm31xpztgevd4ao/MobArena.jar?dl=1). If any of you prefer to build from source yourselves, I can push the changes to a new branch.

**Comment by ScuroK** [comment] 2018-04-29 17:16
@garbagemule i will start testing tonite. probably give u feedback tonite or tmr

**Comment by garbagemule** [comment] 2018-04-30 12:33
Just to recap some of the feedback:

- @Nesseley and I found no issues in our tests
- @ScuroK said that things are working fine for him as well
- @Sikatsu and I _did_ find issues on his setup

So the soft-depend solution didn't seem to do it here. I'll have to look into this a bit more. It's a bit grim-looking, because it does seem like MobArena is doing exactly what it should do, but either PerWorldInventory or Multiverse is throwing a wrench in the gears by adding delays to certain things.

**Comment by garbagemule** [comment] 2018-04-30 15:27
Just so I don't forget, we've made some progress on this issue.

The `separate-gamemode-inventories` setting in PerWorldInventory defaults to `true`, but if we flip it to `false`, everything seems to work as it should. Now, what is this setting...

From what I have gathered, it's really just an extra layer in PWI that allows the plugin to control per-gamemode inventories as well (duh, it's in the name). What's interesting about it is the way it differs from a normal teleport event. It turns out that on a teleport, PWI just loads the inventory for that world, but on a gamemode change, it schedules the processing for [one tick later](https://github.com/Gnat008/PerWorldInventory/blob/7475396b47ed8058ced7df01a5ffde71b99fcfa8/src/main/java/me/gnat008/perworldinventory/listeners/player/PlayerGameModeChangeListener.java#L63).

Now, this doesn't mean that my current changes aren't needed - they are. But it also means that I can't feasible fix this MobArena-side only. If this has to be fixed for gamemode inventories as well, there has to be some sort of inter-plugin communication and some really nasty delayed processing in MobArena.

I think the happy middle ground is that MobArena just simply does not support per-gamemode inventories (at least if it's PWI managing them), and we need to update the documentation to reflect that. Perhaps even some really aggressive fail-fast functionality, if I can find a way to check that setting without scanning config-files (I think plugins might be sandboxed on the filesystem, but not I'm not sure about that).

**Closed** 2018-05-01 22:41 UTC
Labels: bug

**Comment by Gnat008** [comment] 2018-05-02 23:14
Sorry for not chiming in earlier (I'm the PWI guy). Yeah, that whole one tick later thing tends to mess things up when it comes to other plugins. With the upcoming rewrite to PWI, this no longer happens because the process is a bit saner than before. Hopefully with all of our changes, this wont be an issue anymore! :D

**Comment by Gnat008** [comment] 2018-05-02 23:31
Heya!

Sounds good! And thanks, me too!

And no problem; I know the pain of having an issue with something and *not* being able to see for myself. It really does make a lot of things so much easier for everyone.
