### ISSUE TITLE
Using non-LivingEntity entity types throws exception on spawn and breaks the session

### ISSUE THREAD

**Issue by TheIntelloBox** [garbagemule/MobArena#438] opened 2018-03-27 17:54 UTC
* This issue is a…
    * [X] Bug report
    * [ ] Feature request
    * [ ] Documentation request
    * [ ] Other issue
    * [ ] Question
* **Describe the issue / feature in 1-2 sentences**: 

### Bug report

* **MobArena version**:  0.98.1
* **Server version**:  Paper Spigot 1.12.2
* **Plugins**: 

ERROR : When my players kill the boss, the mobs of the next waves don't spawn.
My config.yml :
https://pastebin.com/0m1qD3Pj

**Comment by garbagemule** [comment] 2018-04-07 12:57
Seems like the paste has expired.

Can you please provide some more information about what type of boss this is, how the players kill it, how long the fight lasts for? Your config-file and a server log of the entire session would be most helpful.

I can look into this by the end of April.

**Comment by TheIntelloBox** [comment] 2018-04-07 13:31
https://hastebin.com/foyocaguce.scala

**Comment by garbagemule** [comment] 2018-04-07 13:37
Thanks for the config-file.

There are 9 boss waves in this configuration. Please provide as much of the previously requested information as you can, as it gives me a much better chance at actually fixing this. It's hard to debug something you know nothing about and can't reproduce.

**Comment by TheIntelloBox** [comment] 2018-04-07 13:54
https://pastebin.com/bacRQjK1

**Comment by TheIntelloBox** [comment] 2018-04-18 15:59
Did you see the bug ?

**Comment by garbagemule** [comment] 2018-04-18 16:04
No, I'm still waiting for the details I previously asked.

I can't fix something I can't reproduce, and I can't reproduce something without detailed reproduction steps. Help me so I can help you.

**Comment by TheIntelloBox** [comment] 2018-04-18 18:55
What do you want exactly ? I'm on Java 8, Paper Spigot 1.12.2, latest version of MobArena.

**Comment by garbagemule** [comment] 2018-04-18 18:56
What I asked for in my first and second comments.

**Comment by TheIntelloBox** [comment] 2018-04-20 17:14
Could you send me your Discord or your Skype because I don't want to paste my plugins here.

**Comment by garbagemule** [comment] 2018-04-20 19:41
At any rate, you should try to reproduce the issue on a clean environment. Disable/remove all plugins and try to reproduce the issue. If you can't do it on your live server, make a local one that you can use just for troubleshooting.

Even without a list of plugins, there's still so much information you can provide that you haven't. Please re-read my comments. If there's something you don't understand, please just ask instead of ignoring it. Every piece of information can be the key to figuring out what's wrong.

**Comment by TheIntelloBox** [comment] 2018-04-20 19:55
Did you check my config ?

**Comment by garbagemule** [comment] 2018-04-20 20:13
Yes, did you read my follow up questions?

**Comment by garbagemule** [comment] 2018-04-20 20:38
Okay, let me make it a little more explicit. This back-and-forth is pointless. I need information to help. I want to help, so I need information. I want the following questions answered before I spend any more time on this issue:

- Config-file (this has been provided already)
- Server log of the MobArena session. I don't want a full server log. I want a server log that starts when the first player joins and ends when the arena "stops responding". Everything else is a waste of time.
- Can this be reproduced in a clean environment with no other plugins than MobArena? If yes, then good, I can get started debugging right away. If no, then I need a list of plugins or a copy of the server environment to have a chance at reproducing the issue. There is no other way.
- Which boss from the config-file, specifically, is causing the issue? This answers some of the previously requested pieces of information because I can look in the config-file at that specific boss wave definition and see it.
- What is the duration of the wave prior to the boss wave?
- What is the duration of the boss wave until the boss is killed?
- What is the killing blow on the boss? Sword swing, arrow, TNT?
- How long does the session last before this happens?
- How many players are in the session?
- How many players are alive when the boss wave spawns?
- How many players die during the boss fight?

If you can't provide this kind of detailed information about a bug that clearly should affect many others if it was a core, critical bug, then I'm afraid I can't do anything to help. In that case, I think it's best to close the issue, because we won't get anywhere with it.

**Comment by garbagemule** [comment] 2018-04-20 22:11
Well there is an error in the log that indicates an issue with what MobArena is trying to spawn. Your config file paste has expired. Please post it again. Maybe without an expiration time or with one that's longer.

**Comment by TheIntelloBox** [comment] 2018-04-21 07:57
https://pastebin.com/ufS5qxzZ

**Comment by garbagemule** [comment] 2018-04-21 08:30
Found it!

Line 587 in your config-file, you're using `evoker_fangs` as a possible mob type in the default wave. The "fangs" entity type is not a LivingEntity (a mob, basically), so MobArena breaks after trying to use it as one. Evoker fangs are entities that evokers generate during their fang attack. You should not use them as a mob.

So this is essentially the biggest problem with allowing everything in the EntityType enum to be used as a possible mob - sometimes people do silly things, most often by accident.

It's a bit difficult to prevent this kind of issue without resorting to a type of blacklisting, but I think I may have found a way to get around it with a bit of type checking at load time. I'll elaborate in my next comment.

**Comment by garbagemule** [comment] 2018-04-21 08:32
MACreature internally creates a map of entity names to MACreature instances from the values in the EntityType enum. It just so happens that EntityType has a `getEntityClass()` method that returns the class/interface for the spawned entity. By checking if `LivingEntity.isAssignableFrom(type.getEntityClass())` in the loop in MACreature, we should be able to completely avoid this kind of problem, failing fast with an error during load, rather than failing lazily at runtime.

This is a pretty good first issue for anyone wanting to get involved in the project. Marking it as such.

**Comment by garbagemule** [comment] 2018-04-21 08:38
Just in case the pastes expire again, here's the important bits snipped from the config-file and server log:

config-file (`evoker_fangs` as a monster type in a wave):

        waves:
          recurrent:
            def1:
              type: default
              priority: 1
              frequency: 1
              monsters:
                evoker_fangs: 3

stacktrace from server log:

    [23:06:12] [Server thread/WARN]: [MobArena] Task #32931 for MobArena v0.98.1 generated an exception
    java.lang.ClassCastException: org.bukkit.craftbukkit.v1_12_R1.entity.CraftEvokerFangs cannot be cast to org.bukkit.entity.LivingEntity
        at com.garbagemule.MobArena.waves.MACreature.spawn(MACreature.java:128) ~[MobArena%20(6).jar:?]
        at com.garbagemule.MobArena.MASpawnThread.spawnWave(MASpawnThread.java:167) ~[MobArena%20(6).jar:?]
        at com.garbagemule.MobArena.MASpawnThread.run(MASpawnThread.java:119) ~[MobArena%20(6).jar:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.12.2.jar:git-Paper-1375]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) [patched_1.12.2.jar:git-Paper-1375]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) [patched_1.12.2.jar:git-Paper-1375]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1375]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1375]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1375]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

**Comment by TheIntelloBox** [comment] 2018-04-21 09:55
Thanks it works fine ! :D

**Closed** 2018-08-05 23:00 UTC
Labels: bug, good first issue
