### ISSUE TITLE
Falling out of the arena may kill the player for real

### ISSUE THREAD

**Issue by sepulzera** [garbagemule/MobArena#698] opened 2021-08-18 12:52 UTC
# Bug report

**Short description**

I have an arena, where players can fall out of. If they do, potentially three events can occur:
1. They might be teleported to spectators by the plugin, as they are leaving the arena area. (40 % chance)
2. They might die while still being fighting in the arena. As they died, they will be teleported to spectators. (55 % chance)
3. MobArena detects that they are leaving and teleports them to spectator. They will be removed from the arena. Immediately, they still receive the fall damage and die. For real. (5 % chance)

**Reproduction steps**

1. Build an arena, where players can fall out of, deep down. The arena area should be only the arena, not the whole chunk deep down.
2. Join an arena with /ma join.
3. Hit a sign to pick a class
4. Run out of the arena.

**Details**

* **MobArena version**: 0.106
* **Server version**: Paper 1.16.5-786

**Additional info**

This bug exists for several versions now. I am not quite sure why I didn't report it earlier.
Previously it was on MA 0.102 and Spigot 1.12 or sth like that.

**Comment by garbagemule** [comment] 2021-08-18 17:05
If I'm understanding this right, you're experiencing a problem where players are _correctly_ removed from the arena as they move out of bounds or die, but sometimes die _after_ they have left the arena.

MobArena only makes out-of-bounds checks every so often, so there is a window of time when players and monsters can exist outside the arena region without being removed. This is by design and thus not a bug.

Players dying immediately following the leave procedure sounds like it _could_ be a bug, but I'm not entirely sure it is. It might be a type of "desync" problem between the server and the client, where the server has initiated the teleport, meaning the player _shouldn't_ receive fall damage, but the teleport packet reaches the client too late, so the client thinks the fall damage happens. I don't know enough about the internal workings of the client-server conversation to say if this is indeed the problem or not. It could also be that the player somehow retains their velocity in the teleport. We _may_ be able to do something about that by just overriding the player's velocity before teleporting, but that's just a wild guess.

If it _isn't_ due to velocity retention, it seems like this problem is easily circumvented with a "soft" landing pad. Could you try dumping a pool of water at the bottom of your pit to see if that fixes the issue?

**Comment by sepulzera** [comment] 2021-08-19 08:20
Not quite sure how I could have missed that earlier, but your guess with velocity retention seems to be right on spot.

If the player was falling several blocks without hitting the ground, and then MA teleports him to spectators, the player will receive some fall damage.

**Comment by Maroon28** [comment] 2021-08-19 08:24
Yep, velocity retention would make the most sense. It happens in other plugins too, for example if you're falling and you use essentialsx's `./home` command, you'd still take fall damage. For now, you can probably make a tiny worldguard region where your spectator point is, and disable fall-damage there using a region flag.

**Comment by sepulzera** [comment] 2021-08-19 10:42
> For now, you can probably make a tiny worldguard region where your spectator point is, and disable fall-damage there using a region flag.

That works very well, great idea!

**Comment by garbagemule** [comment] 2021-08-19 21:47
I'll try to see if I can find some time this weekend to try out a potential fix for the velocity retention. If it ends up being too much trouble to try to fix it, I might just opt for a FAQ entry that mentions @Maroon28's workaround, since it seems to actually solve the problem consistently :)

**Comment by garbagemule** [comment] 2021-10-30 09:02
@sepulzera Awesome, thanks for the PR! Do you know if the null vector change is necessary as well? I didn't know about the `setFallDistance()` method, but I assume setting it to 0 will just cancel out any fall damage regardless of the velocity, since it won't have time to build up after the teleport. It would be awesome if we could just plop that in and not worry about the velocity :)

**Comment by sepulzera** [comment] 2021-10-30 09:49
I will give it a shot on next tuesday.

I am not familiar with neither the Bukkit API nor any Minecraft internals. Why do you bother so much about the velocity? (Just curious, as I would assume that resetting both seems to be a definitely safe way to cancel out any strange internal calculations or so. ^^)

**Comment by garbagemule** [comment] 2021-10-30 10:21
That would be awesome, thanks so much :)

The primary reason for leaving out the velocity if it is unnecessary is to keep things neat and tidy. I consider it similar to having a random, unused `int x = 0;` in there. I think it makes the code base easier to understand, maintain, and refractor if it only consists of code that is necessary and sufficient. If the velocity change doesn't do anything, it might as well not be there, but if it is required, we can document it and we will know for sure that velocity and fall distance should go hand in hand next time we encounter a similar issue. All we know right now is that velocity on its own is not enough, but we don't know if fall damage alone is. I hope that makes sense :) 

You might be right about "resetting", though, as most teleports in the plugin work with no regard for velocity and fall distance, implicitly assuming them to be irrelevant or automatically reset. At least the "administrative" teleports like moving to and from the arena. I suppose if someone put a warp one or two blocks above the ground, a high velocity might still be enough to kill or damage the player?

**Comment by sepulzera** [comment] 2021-11-02 22:02
I did some further testing. When only resetting the fall-distance, I didn't die, too. In this regard, resetting the velocity seems to be superfluous.

Furthermore I did some testing about what the resulting velocity will look like, if we don't reset it. As result, I didn't perceive any difference in this regard. I was running with speed:15 in some direction when being teleported to the exit (for leaving the arena). I didn't keep the momentum.

Same goes for falling down. I moved the warp two blocks above the ground. No damage taken.

For this matter, as a result of my testing I assume that resetting the velocity is indeed superfluous. I've updated my PR.

My testing environment:
- paper-1.16.5-786 (MC 1.16.5)
- MobArena 0.106.1-SNAPSHOT
- Java: openjdk 11.0.11 2021-04-20
- Minecraft 1.16.5 with OptiFine

**Comment by garbagemule** [comment] 2022-02-12 15:14
I was able to consistently reproduce the fall damage issue with both `/ma leave` and the out-of-bounds check using an autogenerated arena located high up in the air and with a hole in the floor. The null vector solution did not work, but the fall damage solution did.

I'll try to get your fix merged in @sepulzera, but I did a rebase on this branch, so I'll just try to work around that somehow :P

Thanks for the effort and sorry about the delay!

**Closed** 2022-02-12 15:28 UTC
Labels: type/bug, area/restoration, area/misc
