### ISSUE TITLE
Option to disable inventory restoration for My Items class

### ISSUE THREAD

**Issue by Supergameplayer** [garbagemule/MobArena#614] opened 2020-04-19 00:55 UTC
# Feature request

**Short description**
How this would work is that there would be an option to have changes made in the player's inventory remain after the arena ends or the player leaves or dies. For example, if restore_myitems is set to false then any wear on tools and armor would remain after you're done in the arena. You also wouldn't get back any arrows or potions you used. This would be useful for adding another aspect of difficulty in an arena, or having a player's stat tracking items work properly.

**Implementation details**
There would be an option in the arena config file known as restore_myitems that would default to true, where any changes while using the My Items class would be restored after the player's run in the arena. If it's set to false, any inventory changes made would be kept after a player's run in the arena.

**Additional info**
None

**Comment by garbagemule** [comment] 2020-04-19 06:40
Duplicate of #552

**Closed by garbagemule** 2020-04-19 06:40 UTC
