### ISSUE TITLE
Death Animation bug on spigot 1.12

### ISSUE THREAD

**Issue by Sikatsu** [garbagemule/MobArena#437] opened 2018-03-15 09:31 UTC
* This issue is a…
    * [x] Bug report
    * [ ] Feature request
    * [ ] Documentation request
    * [ ] Other issue
    * [ ] Question

* **Describe the issue / feature in 1-2 sentences**: 
If you die in the MobArena your character is bugging out even after you leave the MobArena: http://prntscr.com/irh3q8

Until I relog on the server I walk and play with the death animation.

* **MobArena version**: 0.99
* **Server version**: Spigot 1.12
* **Plugins**: -

**Comment by Sikatsu** [comment] 2018-03-15 10:26
Turns out the death animation is stuck whenever you die. Even when you die with force /ma leave.

**Comment by Sikatsu** [comment] 2018-03-15 10:54
@garbagemule @slipcor

**Comment by Haileykins** [comment] 2018-04-03 23:28
I have seen this myself, and I can't figure out what is causing it, I have tried to even turn off autorespawn yet still it happens, and nothing in the code obviously jumps out at me for how to remedy the issue.

**Comment by jflory7** [comment] 2018-04-04 19:59
@Sikatsu Thank you for filing the issue. @Haileykins Thanks for also confirming it.

I marked it as a bug, but my ability to debug is limited. I am not aware of any major changes made in the last few releases that would trigger this, so I wonder if the bug is created by something new in Spigot.

Hopefully @garbagemule can offer debug advice here.

**Comment by Haileykins** [comment] 2018-04-05 16:02
@jflory7 much appriciated

**Comment by garbagemule** [comment] 2018-04-07 12:55
I'll check up on this as the first thing I do when I dig back in at the end of April.

Thanks for reporting @Sikatsu and confirming @Haileykins :)

**Comment by garbagemule** [comment] 2018-04-21 09:49
Forgot to add it to the sweep. It's in there now.

**Comment by garbagemule** [comment] 2018-04-23 08:51
@Sikatsu @Haileykins 
I just tried this on Craftbukkit 1.12.2, and I can reproduce it if I set `auto-respawn: true` in my config-file. If I set it to `false`, however, I respawn just fine. Can you guys please check if this is the case for you as well?

Hailey, you did say that you tried turning it off, but can you please try again and see if maybe it's just a fluke of sorts?

**Comment by garbagemule** [comment] 2018-04-23 09:16
It looks like this is only a client-side glitch, so there's nothing "dangerous" about it. When you are glitched, you are the only one who can see it - others can't. At least from what I just experienced on a MobArena server.

**Comment by garbagemule** [comment] 2018-05-06 17:47
So we looked into this a bit more a week ago, and we found that this issue is very situational and impossible to reproduce consistently across setups - I haven't yet been able to reproduce it locally, but on Sikatsu's setup it happens all the time. So long as we can't reproduce it consistently across setups, there isn't really anything we can do about it.

We also found through a bit of Googling on the issue that it is not unique to MobArena, and that it can happen even on semi-clean setups with barely any plugins. Suggested solutions range from dirty packet tinkering (not going to happen in MobArena) to faux events (highly prone to unexpected side effects). It seems like it might be something that can't actually be fixed server-side, and that it's a client-specific glitch.

Marking as needs feedback, as the problem _space_ isn't well-defined even though the issue itself is very apparent.

**Comment by GiraffeCubed** [comment] 2018-06-04 15:07
@garbagemule 

> I just tried this on Craftbukkit 1.12.2, and I can reproduce it if I set auto-respawn: true in my config-file. If I set it to false, however, I respawn just fine. Can you guys please check if this is the case for you as well?

I can confirm that this issue only occurs for me when auto-respawn: true, every time I die.

**Comment by garbagemule** [comment] 2018-06-04 19:27
@GiraffeCubed how do you force respawns elsewhere? With plugins? MobArena heals you and teleports you out of the arena. That's basically it. If there is a different approach in other plugins, maybe MobArena can copy it (unless it involves tinkering with packets).

**Comment by GiraffeCubed** [comment] 2018-06-05 15:06
Using this

((Player)this.player.getSingle(e)).spigot().respawn();
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Player.Spigot.html#respawn--

In testing, when I heal the player on death, if the heal is not instant and has any delay whatsoever, the bug occurs.

Is your heal or revive on death in MobArena delayed?

**Comment by garbagemule** [comment] 2018-06-05 18:56
We can't use the .spigot() method in MobArena because that's in the Spigot API rather than the Bukkit API. I saw some mention of it on the forums as well.

As for delays, it looks like the heal is not delayed, but the "revive" (whatever that entails exactly is left as an exercise for the reader) is, but I will admit that I don't know why. Probably something to do with other things, but I guess it's worth trying not to do.

**Comment by garbagemule** [comment] 2019-08-05 18:23
Closing this since 1.12 is sort of going out of style, and auto-respawn is removed from the next release onward.

**Closed by garbagemule** 2019-08-05 18:23 UTC
Labels: bug, needs feedback
