### ISSUE TITLE
[SUGGESTION] Mythic Mobs integration

### ISSUE THREAD

**Issue by CraftyBr** [garbagemule/MobArena#458] opened 2018-05-04 18:41 UTC
* This issue is a…
    * [ ] Bug report
    * [X] Feature request
    * [ ] Documentation request
    * [ ] Other issue
    * [ ] Question
* **Describe the feature in 1-2 sentences**: 
Allow the spawning of Mythic Mobs inside the arena. 
Plugin: https://www.spigotmc.org/resources/%E2%9A%94-mythicmobs-%E2%96%BAthe-1-custom-mob-creator%E2%97%84.5702/
* **Feature type**:
    * [ ] Arena configuration
    * [ ] Classes
    * [ ] Documentation
    * [ ] Economy integration
    * [ ] Leaderboards
    * [ ] New config settings
    * [ ] Other (please explain)
    * [ ] Rewards
    * [X] Third-party plugin support

**What does it do?**: 
It supports custom mobs inside the arena.
**Does it need new or changed commands? What are they?**: 
It requires no new commands but maybe a new line in the config "MythicMobs: true/false"
**Does this feature affect other parts of MobArena?**: 
it should only allow the spawning of Mythic Mobs or custom vanilla mobs (via MythicMobs)

**Comment by PrinceOfIonia** [comment] 2018-05-04 19:14
How would you tell the arena to spawn a specific type of Mythic Mob?

**Comment by CraftyBr** [comment] 2018-05-04 19:18
As I am not a developer, I would not know. But maybe in the config for "waves" have Monsters: <mythicmob name> and under the category of settings have a toggle for them "MythicMobs: true/false"

**Comment by PrinceOfIonia** [comment] 2018-05-04 19:27
Yeah, you've explained this, already, you're telling the arena to turn on compatibility with Mythic Mobs, but you haven't presented a method on how to tell the arena to use the mob at all, or what wave to spawn it.

Something needs to tell it. Perhaps, in the config file, in settings the monsters in the wave, instead of a regular zombie, it might be possible to do it like this. http://prntscr.com/jdtdec

Ice Zombie is my example Mythic Mob.

**Comment by garbagemule** [comment] 2018-05-06 16:53
Duplicate of #362

Please check if your suggestion has already been posted before creating new issues. Closing this one as the old one has more useful comments.

**Closed by garbagemule** 2018-05-06 16:53 UTC
