### ISSUE TITLE
Some mob types and abilities breaking blocks in arenas and not restoring them when complete

### ISSUE THREAD

**Issue by DiscoveriesMC** [garbagemule/MobArena#270] opened 2015-08-15 15:00 UTC
I noticed that there were a few holes in my arenas from the exploding red sheep and the obsidian-bomb ability. I have the config set to restore the arena but there are still broken blocks not being regenerated. Using Spigot 1.8.8

**Comment by garbagemule** [comment] 2015-08-15 16:33
This is fixed in the next release :)

**Comment by DiscoveriesMC** [comment] 2015-08-15 17:34
That's great! Do you have any update on when that release will be? Also is it possible to add an option to change the [MobArena] prefix for all chat messages? I have a lot of suggestions using a lot of the new features like titles and such as well, if you're interested! :)

**Comment by JBTollak** [comment] 2015-08-18 14:56
I can confirm that damage made by Exploding Sheeps, and the obsidian bomb ability does not rollback damaged blocks when arena ends.
You can add Powered Creepers to the list as well.

Looking forward to the next release.
Keep up the good work, it is very much appreciated!

**Comment by garbagemule** [comment] 2015-08-19 14:28
I've just uploaded v0.97 to DBO, so whenever it is approved. If you are adventurous (read: if you aren't a paranoid freak who thinks that I would all of a sudden add malicious code to my own project), here's a link to the file page, accessible before approval: http://dev.bukkit.org/bukkit-plugins/mobarena/files/37/

Closing this issue, since it has been fixed :)

**Closed by garbagemule** 2015-08-19 14:28 UTC
