### ISSUE TITLE
Players respawn at the end of a round instead of dying or get revived

### ISSUE THREAD

**Issue by xWaffles** [garbagemule/MobArena#582] opened 2019-11-17 14:55 UTC
# Feature request

Mob Arena should make it so when a player can respawn on next wave if other players are still alive and have completed the current wave. There also can be a separate setting for players to revive other dead players.

For example, Player X and Y are playing together and Player X dies on a wave and a death message is shown but Player Y is still fighting and defeats the wave. Player X spawns at the start of the next wave with all the previous items they had before they died. Another optional feature is that Player X is knocked out and a message is shown saying Player X is knocked out and Player Y needs to go to Player X's Body and shift to revive them before a timer runs out. When the timer runs out, Player X respawns at the start of the next wave is Player Y is still alive and defeats the current wave

The player who died should be sent to the spectator area and can wait till the other player defeats them. If the player fails to do so then the arena is ended. If the reviving feature is enabled then, Player X should be frozen in the place where they died with a hologram above their heads with the timer and instructions and Player Y needs to run to them and shift for a certain amount of time till they respawn.

The Respawn at the end of the Wave feature and the Reviving feature can be separate per-arena settings but reviving cannot be enabled without the other setting

This will make it more fun and easier as people don't always get kicked when they die and can stay playing for longer.

**Comment by garbagemule** [comment] 2019-11-24 16:54
Thanks!

We actually had a good chat about this thing in the last MobArena Jam. I think the conclusion was that this is a pretty good candidate for a feature that the sessions rework should give way to. It's pretty clear that the wait time after death is super boring, which kills a lot of fun. But it should be up to server owners if they want revive functionality or not, and it needs to be a per-arena thing.

**Comment by garbagemule** [comment] 2020-08-09 10:28
Turns out this was a duplicate of #517. Closing.

**Closed by garbagemule** 2020-08-09 10:28 UTC
Labels: area/sessions, blocked/rework, rework/sessions, type/enhancement
