### ISSUE TITLE
Ability for mobs/bosses to wear armor

### ISSUE THREAD

**Issue by PlayMoree** [garbagemule/MobArena#530] opened 2019-05-11 15:50 UTC
#Ability for bosses to wear armor

**Short description**
 Ability to add selected armor to waves/bosses to widen our creativity with bosses. 

**Implementation details**
Example would be "Armor: Dimond_Helmet, Diamond_Chestplate" Now when the boss spawns he would be wearing a diamond_helmet and diamond_chestplate, Also "Equiped: Diamond_Sword" so we can give them a knockback weapon

**Additional info**
Nope

**Comment by eiglow** [comment] 2019-05-14 01:49
Having the ability to give items to mobs in general would be quite useful, like making drowned spawn with tridents or skeletons spawn with bows that have specific enchantments.

**Comment by garbagemule** [comment] 2019-06-08 08:48
Duplicate of https://github.com/garbagemule/MobArena/issues/351

**Closed by garbagemule** 2019-06-08 08:48 UTC
