### ISSUE TITLE
entityExplode overide LWC and WorldGuard explode protection

### ISSUE THREAD

**Issue by lackooka** [garbagemule/MobArena#704] opened 2021-09-24 14:21 UTC
# Bug report

**Short description**

When the plugin is active, the LWC and the Worldguard proctects are just overide in global because it is Highest priority.

I found in the code which is in the MAGlobalListener.class at 193th and 199th line:

    @EventHandler(priority = EventPriority.HIGHEST)
    public void entityExplode(EntityExplodeEvent event) {
        for (Arena arena : am.getArenas())
            arena.getEventListener().onEntityExplode(event);
    }

    @EventHandler(priority = EventPriority.HIGHEST)
    public void blockExplode(BlockExplodeEvent event) {
        // Create a copy of the block list so we can clear and re-add
        List<Block> blocks = new ArrayList<>(event.blockList());

        // Account for Spigot's messy extra event
        EntityExplodeEvent fake = new EntityExplodeEvent(null, event.getBlock().getLocation(), blocks, event.getYield());
        entityExplode(fake);

        // Copy the values over
        event.setCancelled(fake.isCancelled());
        event.blockList().clear();
        event.blockList().addAll(fake.blockList());
        event.setYield(fake.getYield());
    }

**Reproduction steps**

1. Place a bed in nether or place respawn anchor on overworld
2. Explode them near an worldguard and/or LWC protected place (I tried that without any permission)
3. It just explode them when these block are procected by LWC and/or Worldguard.

**Details**

MobArena version: 0.106
LWC Version: 2.2.7-ad0f824
WorldGuard version: 7.0.5+3827266
Server version: Paper 1.16.5-649

**Additional info**

I just replace the HIGHEST to LOWEST and then it is not exploded.
If you want to see them, I can send you videos of it.

**Comment by Nesseley** [comment] 2021-09-24 15:10
Just linking to this previous issue in case its of any usage on this issue.  #697

**Comment by garbagemule** [comment] 2021-09-24 15:12
We recently had #697 conclude with a "cannot reproduce" conclusion from the person reporting the issue, so it's nice to see another set of reproduction steps that might bring about some sort of clear solution.

That solution is **not** to lower the priority, however. That would break so many other things.

I can see that my last comment on the other issue mentioned the cancel state from the input event not being copied over. Could you try that _instead_ of changing the priority to see if that also fixes the problem? Just add`fake.setCancelled(event.isCancelled());` between these two lines:

```java
EntityExplodeEvent fake = new EntityExplodeEvent(null, event.getBlock().getLocation(), blocks, event.getYield());
entityExplode(fake);
```

**Comment by lackooka** [comment] 2021-09-24 16:55
I added it, and it works at the moment. I hope it could be stay in this option.

**Comment by garbagemule** [comment] 2021-09-25 22:41
I think we should get this fix implemented and tested before closing the issue :)

**Closed** 2021-12-05 16:40 UTC
Labels: type/bug, area/misc
