### ISSUE TITLE
exception, 1.12.2

### ISSUE THREAD

**Issue by Kbryst** [garbagemule/MobArena#648] opened 2020-11-07 01:54 UTC
**Short description**
Just seeing this in console pretty often while a game is active, it looks like the signs are updating fine. We only use last wave, damage taken, and hits on the leaderboards, and we have a join sign in place.

**Details**

* **MobArena version**: 0.104.2
* **Server version**: Paper spigot 1.12.2
* **Stacktrace** (if applicable): https://pastebin.com/T7ba3WcJ

**Comment by garbagemule** [comment] 2020-11-07 07:09
Thanks for the report! 

This looks like a semi-duplicate of #645. The location stored for an arena sign in signs.data points to a world that either no longer exists or doesn't exist by the time MobArena loads. If `/ma reload` fixes the problem, it's the latter, otherwise it's the former.

I'm gonna close this as a duplicate since the other issue already contains a breakdown of the problem.

**Closed by garbagemule** 2020-11-07 07:09 UTC
